In [1]:
!pip install tensorflow-gpu==2.0.0-alpha0
import tensorflow as tf

print(tf.__version__)

    100% |████████████████████████████████| 332.1MB 86kB/s 
    100% |████████████████████████████████| 61kB 23.1MB/s 
    100% |████████████████████████████████| 3.0MB 7.7MB/s 
    100% |████████████████████████████████| 419kB 11.4MB/s 
2.0.0-alpha0


In [2]:
print(tf.__version__)
print(tf.executing_eagerly())
print(tf.keras.__version__)

2.0.0-alpha0
True
2.2.4-tf


In [3]:
var = tf.Variable([3, 3])
if tf.test.is_gpu_available():
    print(var.device.endswith('GPU:1'))
else:
    print("Run on CPU")

False


In [4]:
t2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ])
t3 = tf.reshape(t2, [1, 12])
print(t2.shape)
print(t3.shape)
print(t2[1,1,2])

(2, 2, 3)
(1, 12)
tf.Tensor(11.0, shape=(), dtype=float32)


In [5]:
print(tf.size(t2).numpy())

12


In [0]:
t3 = t2 * 4

In [7]:
tf.math.squared_difference(t3, t2)

<tf.Tensor: id=31, shape=(2, 2, 3), dtype=float32, numpy=
array([[[   0.,    9.,   36.],
        [  81.,  144.,  225.]],

       [[ 324.,  441.,  576.],
        [ 729.,  900., 1089.]]], dtype=float32)>

In [12]:
t3

<tf.Tensor: id=29, shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.,  4.,  8.],
        [12., 16., 20.]],

       [[24., 28., 32.],
        [36., 40., 44.]]], dtype=float32)>

In [16]:
tf.reduce_mean(t3, axis=1, keepdims=True)

<tf.Tensor: id=54, shape=(2, 1, 3), dtype=float32, numpy=
array([[[ 6., 10., 14.]],

       [[30., 34., 38.]]], dtype=float32)>