In [3]:
!pip install tensorflow-gpu==2.0.0-alpha0
import tensorflow as tf

print(tf.__version__)

    100% |████████████████████████████████| 332.1MB 32kB/s 
    100% |████████████████████████████████| 419kB 11.0MB/s 
    100% |████████████████████████████████| 3.0MB 1.1MB/s 
    100% |████████████████████████████████| 61kB 28.1MB/s 
2.0.0-alpha0


In [2]:
print(tf.__version__)
print(tf.executing_eagerly())
print(tf.keras.__version__)

2.0.0-alpha0
True
2.2.4-tf


In [3]:
var = tf.Variable([3, 3])
if tf.test.is_gpu_available():
    print(var.device.endswith('GPU:1'))
else:
    print("Run on CPU")

False


In [4]:
t2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ])
t3 = tf.reshape(t2, [1, 12])
print(t2.shape)
print(t3.shape)
print(t2[1,1,2])

(2, 2, 3)
(1, 12)
tf.Tensor(11.0, shape=(), dtype=float32)


In [5]:
print(tf.size(t2).numpy())

12


In [0]:
t3 = t2 * 4

In [7]:
tf.math.squared_difference(t3, t2)

<tf.Tensor: id=31, shape=(2, 2, 3), dtype=float32, numpy=
array([[[   0.,    9.,   36.],
        [  81.,  144.,  225.]],

       [[ 324.,  441.,  576.],
        [ 729.,  900., 1089.]]], dtype=float32)>

In [8]:
t3

<tf.Tensor: id=29, shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.,  4.,  8.],
        [12., 16., 20.]],

       [[24., 28., 32.],
        [36., 40., 44.]]], dtype=float32)>

In [9]:
tf.reduce_mean(t3, axis=1, keepdims=True)

<tf.Tensor: id=35, shape=(2, 1, 3), dtype=float32, numpy=
array([[[ 6., 10., 14.]],

       [[30., 34., 38.]]], dtype=float32)>

In [0]:
dice1 = tf.Variable(tf.random.uniform([10,1], 1, 6, seed=42))
dice2 = tf.Variable(tf.random.uniform([10,1], 1, 6, seed=4))
sum_val = dice1 + dice2

con = tf.concat(values=[dice1, dice2, sum_val], axis=1)

In [11]:
con

<tf.Tensor: id=69, shape=(10, 3), dtype=float32, numpy=
array([[ 5.7613573,  5.7829084, 11.544266 ],
       [ 4.3870387,  2.334054 ,  6.7210927],
       [ 4.976591 ,  5.988989 , 10.96558  ],
       [ 4.7789087,  5.229465 , 10.008373 ],
       [ 3.379778 ,  1.1509184,  4.5306964],
       [ 4.155074 ,  2.4473443,  6.6024184],
       [ 1.9301019,  4.5956306,  6.5257325],
       [ 1.5715388,  5.2020426,  6.7735815],
       [ 2.681109 ,  2.6014438,  5.2825527],
       [ 4.6166754,  2.3770688,  6.993744 ]], dtype=float32)>

In [13]:
var = tf.Variable([1,2,3])
check = tf.train.Checkpoint(var=var)
save = check.save('./')
var.assign([0,0,0])
print(var)
check.restore(save)
print(var)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 0, 0], dtype=int32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [0]:
def f1(t1, t2):
    return tf.reduce_mean(tf.multiply(t1,t2), axis=None)

f2 = tf.function(f1)

t1 = tf.Variable([1,2,3])
t2 = tf.Variable([4,5,6])

assert f1(t1, t2).numpy() == f2(t1, t2).numpy()

### MNIST with TF 2.0


In [5]:
# Load the data
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize the data
x_train, x_test = tf.cast(x_train/255.0, tf.float32), tf.cast(x_test/255.0, tf.float32)
y_train, y_test = tf.cast(y_train/255.0, tf.int64), tf.cast(y_test/255.0, tf.int64)

11493376/11490434 [==============================] - 0s 0us/step


In [0]:
model1 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

In [0]:
model1.compile(optimizer=tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [23]:
model1.fit(x_train, y_train, batch_size=32, epochs=10)

Epoch 1/10
60000/60000 [==============================] - 6s 101us/sample - loss: 0.0020 - accuracy: 0.9995
Epoch 2/10
60000/60000 [==============================] - 6s 104us/sample - loss: 7.0533e-07 - accuracy: 1.0000
Epoch 3/10
60000/60000 [==============================] - 6s 95us/sample - loss: 2.0946e-07 - accuracy: 1.0000
Epoch 4/10
60000/60000 [==============================] - 5s 89us/sample - loss: 1.2160e-07 - accuracy: 1.0000
Epoch 5/10
60000/60000 [==============================] - 5s 89us/sample - loss: 4.2551e-08 - accuracy: 1.0000
Epoch 6/10
60000/60000 [==============================] - 5s 89us/sample - loss: 1.1026e-08 - accuracy: 1.0000
Epoch 7/10
60000/60000 [==============================] - 5s 88us/sample - loss: 3.4630e-09 - accuracy: 1.0000
Epoch 8/10
60000/60000 [==============================] - 5s 88us/sample - loss: 2.6007e-09 - accuracy: 1.0000
Epoch 9/10
60000/60000 [==============================] - 5s 88us/sample - loss: 2.2351e-09 - accuracy: 1.0000
Epo

In [24]:
model1.evaluate(x_test, y_test)

10000/10000 [==============================] - 1s 61us/sample - loss: 1.6689e-10 - accuracy: 1.0000


[1.6689292579030734e-10, 1.0]

In [26]:
model1.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_2 (Flatten)          multiple                  0         
_________________________________________________________________
dense_4 (Dense)              multiple                  401920    
_________________________________________________________________
dropout_2 (Dropout)          multiple                  0         
_________________________________________________________________
dense_5 (Dense)              multiple                  5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


### Using the Functional API

In [0]:
inputs = tf.keras.Input(shape=(28,28)) # Placeholder tensor
x = tf.keras.layers.Flatten()(inputs)
x = tf.keras.layers.Dense(512, activation=tf.nn.relu)(x)
x = tf.keras.layers.Dropout(0.2)(x)
outputs = tf.keras.layers.Dense(10, activation=tf.nn.softmax)(x)
model2 = tf.keras.Model(inputs=inputs, outputs=outputs)

In [28]:
model2.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 28, 28)]          0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 512)               401920    
_________________________________________________________________
dropout_3 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_7 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


### Subclassing the model

In [0]:
class MyModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(MyModel, self).__init__()
        inputs = tf.keras.Input(shape=(28,28))
        self.x0 = tf.keras.layers.Flatten()
        self.x1 = tf.keras.layers.Dense(512, activation=tf.nn.relu)
        self.x2 = tf.keras.layers.Dropout(0.2)
        self.outputs = tf.keras.layers.Dense(10, activation=tf.nn.softmax)
 
    def call(self, inputs):
        x = self.x0(inputs)
        x = self.x1(x)
        x = self.x2(x)
        return self.outputs(x)

In [15]:
model3 = ModelSubClass()
model3.compile(optimizer=tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model3.fit(x_train, y_train, batch_size=32, epochs=5)

Epoch 1/5
60000/60000 [==============================] - 6s 97us/sample - loss: 0.0022 - accuracy: 0.9996
Epoch 2/5
60000/60000 [==============================] - 6s 97us/sample - loss: 3.3479e-07 - accuracy: 1.0000
Epoch 3/5
60000/60000 [==============================] - 5s 87us/sample - loss: 3.5305e-07 - accuracy: 1.0000
Epoch 4/5
60000/60000 [==============================] - 5s 86us/sample - loss: 1.0769e-07 - accuracy: 1.0000
Epoch 5/5
60000/60000 [==============================] - 5s 86us/sample - loss: 2.9306e-08 - accuracy: 1.0000


In [17]:
model3.evaluate(x_test, y_test)

10000/10000 [==============================] - 1s 59us/sample - loss: 4.6492e-10 - accuracy: 1.0000


[4.6491581997543106e-10, 1.0]